name: dev app

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/web-prod.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:    
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: |
        npm install
      working-directory: web
    - name: Build
      run: |
        npm run build
      working-directory: web
      env:
        CI: ""
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
